sales:
  outputs:
    iris:
      type: iris
      threads: 1
      hostname: localhost
      port: 1972
      username: SuperUser
      password: SYS
      namespace: USER
      schema: dbt
  target: iris
