sales:
  outputs:
    iris:
      type: iris
      threads: 1
      hostname: iris
      port: 1972
      username: SuperUser
      password: SYSYS
      namespace: USER
      schema: dbt
  target: iris
