sales:
  outputs:
    iris:
      type: iris
      threads: 1
      hostname: localhost
      port: 1972
      username: SuperUser
      password: SYSYS
      namespace: USER
      schema: hb1
  target: iris
