version: 2  # This specifies the dbt version the configuration is compatible with

sources:
  - name: iris  # A friendly name for your source  # Replace with the actual database name
    schema: sqluser  # Replace with the actual schema name (if applicable)
    tables:  # List of tables from your InterSystems IRIS database
      - name: orders
      - name: customers
      - name: products
      - name: orderitems
